#!/usr/bin/env python3
"""Generate a Wavefront .obj of the X-Seed silhouette.

Produces a hollow truncated cone (the tower) sitting on a thick cylindrical
disc (the sea base). Stdlib only. Run from this directory:

    python3 generate_silhouette.py

The output file path can be overridden with a single positional argument.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

# --- parameters (metres) ----------------------------------------------------

BASE_RADIUS = 3000.0       # sea-base disc radius
BASE_THICKNESS = 50.0      # sea-base disc thickness
TOWER_BASE_RADIUS = 3000.0 # truncated-cone base radius (sits on the disc)
TOWER_TOP_RADIUS = 50.0    # truncated-cone top radius
TOWER_HEIGHT = 4000.0      # truncated-cone height
RADIAL_SEGMENTS = 32       # number of radial subdivisions

DEFAULT_OUTPUT = Path(__file__).with_name("x-seed-silhouette.obj")


def ring(radius: float, z: float, segments: int) -> list[tuple[float, float, float]]:
    """Return `segments` points evenly spaced around a horizontal circle."""
    pts = []
    for i in range(segments):
        theta = 2.0 * math.pi * i / segments
        pts.append((radius * math.cos(theta), radius * math.sin(theta), z))
    return pts


def build_mesh(segments: int):
    """Return (vertices, faces) for the silhouette.

    Vertices are 1-indexed in the returned faces, matching .obj convention.
    Faces are quads where natural, triangles for the disc fans.
    """
    vertices: list[tuple[float, float, float]] = []
    faces: list[tuple[int, ...]] = []

    # --- sea-base disc: bottom ring, top ring, two centre points -----------
    base_bottom = ring(BASE_RADIUS, 0.0, segments)
    base_top = ring(BASE_RADIUS, BASE_THICKNESS, segments)
    vertices.extend(base_bottom)
    vertices.extend(base_top)
    bb_start = 1
    bt_start = bb_start + segments

    vertices.append((0.0, 0.0, 0.0))            # bottom centre
    vertices.append((0.0, 0.0, BASE_THICKNESS)) # top centre
    bb_centre = bt_start + segments
    bt_centre = bb_centre + 1

    # disc bottom fan (normals point down — winding chosen accordingly)
    for i in range(segments):
        a = bb_start + i
        b = bb_start + (i + 1) % segments
        faces.append((bb_centre, b, a))

    # disc top fan
    for i in range(segments):
        a = bt_start + i
        b = bt_start + (i + 1) % segments
        faces.append((bt_centre, a, b))

    # disc side wall (quads)
    for i in range(segments):
        a = bb_start + i
        b = bb_start + (i + 1) % segments
        c = bt_start + (i + 1) % segments
        d = bt_start + i
        faces.append((a, b, c, d))

    # --- truncated cone tower ----------------------------------------------
    tower_z0 = BASE_THICKNESS
    tower_z1 = BASE_THICKNESS + TOWER_HEIGHT

    cone_bottom = ring(TOWER_BASE_RADIUS, tower_z0, segments)
    cone_top = ring(TOWER_TOP_RADIUS, tower_z1, segments)
    cb_start = bt_centre + 1
    vertices.extend(cone_bottom)
    ct_start = cb_start + segments
    vertices.extend(cone_top)

    vertices.append((0.0, 0.0, tower_z1))  # top cap centre
    ct_centre = ct_start + segments

    # cone side wall (quads)
    for i in range(segments):
        a = cb_start + i
        b = cb_start + (i + 1) % segments
        c = ct_start + (i + 1) % segments
        d = ct_start + i
        faces.append((a, b, c, d))

    # cone top cap fan
    for i in range(segments):
        a = ct_start + i
        b = ct_start + (i + 1) % segments
        faces.append((ct_centre, a, b))

    # NOTE: no cone bottom cap — it coincides with the disc top, which is
    # already closed. Keeping it open avoids z-fighting in renders.

    return vertices, faces


def write_obj(path: Path, vertices, faces) -> None:
    lines = [
        "# X-Seed silhouette — generated by generate_silhouette.py",
        f"# {len(vertices)} vertices, {len(faces)} faces",
        f"# units: metres. base_radius={BASE_RADIUS}, tower_height={TOWER_HEIGHT}",
        "o x_seed_silhouette",
    ]
    for x, y, z in vertices:
        lines.append(f"v {x:.4f} {y:.4f} {z:.4f}")
    for face in faces:
        lines.append("f " + " ".join(str(i) for i in face))
    path.write_text("\n".join(lines) + "\n")


def main(argv: list[str]) -> int:
    out_path = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUTPUT
    vertices, faces = build_mesh(RADIAL_SEGMENTS)
    write_obj(out_path, vertices, faces)
    print(f"wrote {out_path} ({len(vertices)} vertices, {len(faces)} faces)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
